apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istiod
  namespace: istio-system
spec:
  dnsNames:
  - istiod.istio-system.svc
  uris:
    - spiffe://cluster.local/ns/istio-system/sa/istiod-service-account
  secretName: istiod-tls
  # Here we use a duration of 1 hour by default based on NIST 800-204A
  # recommendations (SM-DR13).
  # https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-204A.pdf
  # Warning: cert-manager does not allow a duration on Certificates of less
  # than 1 hour.
  duration: {{ .Values.app.tls.istiodCertificateDuration }}
  renewBefore: 30m
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 2048
  revisionHistoryLimit: 1
  issuerRef:
    name: {{ .Values.app.certmanager.issuer.name }}
    kind: {{ .Values.app.certmanager.issuer.kind }}
    group: {{ .Values.app.certmanager.issuer.group }}
