apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-manager-istio-csr.name" . }}
  labels:
{{ include "cert-manager-istio-csr.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cert-manager-istio-csr.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cert-manager-istio-csr.name" . }}
    spec:
      serviceAccountName: {{ include "cert-manager-istio-csr.name" . }}
      containers:
      - name: {{ include "cert-manager-istio-csr.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.agent.servingPort }}
        readinessProbe:
          httpGet:
            port: {{.Values.agent.readinessProbe.port}}
            path: {{.Values.agent.readinessProbe.path}}
          initialDelaySeconds: 3
          periodSeconds: 7
        command: ["cert-manager-istio-csr"]
        args:
          - "--log-level={{.Values.agent.logLevel}}"
          - "--readiness-probe-port={{.Values.agent.readinessProbe.port}}"
          - "--readiness-probe-path={{.Values.agent.readinessProbe.path}}"

          - "--serving-address={{.Values.agent.servingAddress}}:{{.Values.agent.servingPort}}"
          - "--serving-certificate-duration={{.Values.agent.certificateDuration}}"
          - "--root-ca-configmap-name={{.Values.agent.rootCAConfigMapName}}"

          - "--certificate-namespace={{.Values.certificate.namespace}}"
          - "--issuer-group={{.Values.certificate.group}}"
          - "--issuer-kind={{.Values.certificate.kind}}"
          - "--issuer-name={{.Values.certificate.name}}"
          - "--max-client-certificate-duration={{.Values.certificate.maxDuration}}"
          - "--preserve-certificate-requests={{.Values.certificate.preserveCertificateRequests}}"

        {{- if .Values.certificate.rootCA }}
          - "--root-ca-file=/etc/cert-manager-istio-csr"

        volumeMounts:
          - name: root-ca
            mountPath: /etc/cert-manager-istio-csr
        {{- end  }}

        resources:
          {{- toYaml .Values.resources | nindent 12 }}

      {{- if .Values.certificate.rootCA }}
      volumes:
        - name: root-ca
          configMap:
            name: cert-manager-istio-csr-root-ca
            items:
            - key: ca.pem
              path: ca.pem
      {{- end  }}


