apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-manager-istio-agent.name" . }}
  labels:
{{ include "cert-manager-istio-agent.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cert-manager-istio-agent.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cert-manager-istio-agent.name" . }}
    spec:
      serviceAccountName: {{ include "cert-manager-istio-agent.name" . }}
      containers:
      - name: {{ include "cert-manager-istio-agent.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.agent.servingPort }}
        readinessProbe:
          httpGet:
            port: {{.Values.agent.readinessProbe.port}}
            path: {{.Values.agent.readinessProbe.path}}
          initialDelaySeconds: 3
          periodSeconds: 7
        command: ["cert-manager-istio-agent"]
        args:
          - "--log-level={{.Values.agent.logLevel}}"
          - "--healthz-port={{.Values.agent.readinessProbe.port}}"
          - "--healthz-path={{.Values.agent.readinessProbe.path}}"

            ## TODO: allow for mounting custom root CA- "--root-ca-file=
          - "--serving-address={{.Values.agent.servingAddress}}:{{.Values.agent.servingPort}}"
          - "--serving-certificate-duration={{.Values.agent.certificateDuration}}"
          - "--root-ca-configmap-name={{.Values.agent.rootCAConfigMapName}}"

          - "--certificate-namespace={{.Values.certificate.namespace}}"
          - "--issuer-group={{.Values.certificate.group}}"
          - "--issuer-kind={{.Values.certificate.kind}}"
          - "--issuer-name={{.Values.certificate.name}}"
          - "--max-client-certificate-duration={{.Values.certificate.maxDuration}}"
          - "--preserve-certificate-requests={{.Values.certificate.preserveCertificateRequests}}"


        resources:
          {{- toYaml .Values.resources | nindent 12 }}
