kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "cert-manager-istio-agent.labels" . | indent 4 }}
  name: {{ include "cert-manager-istio-agent.name" . }}
  namespace: {{ .Values.certificate.namespace }}
rules:
- apiGroups:
  - "cert-manager.io"
  resources:
  - "certificaterequests"
  verbs:
  - "get"
  - "list"
  - "create"
  - "update"
  - "delete"
