apiVersion: v1
kind: ServiceAccount
{{- if .Values.image.pullSecret != "" }}
  imagePullSecrets:
    - name: {{ .Values.image.pullSecretName }}
{{- end }}
metadata:
  labels:
{{ include "cert-manager-istio-csr.labels" . | indent 4 }}
  name: {{ include "cert-manager-istio-csr.name" . }}
